-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 12:23:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokemon_place
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pokemon_place
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokemon_place` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pokemon_place
-- -----------------------------------------------------
USE `pokemon_place` ;

-- -----------------------------------------------------
-- Table `pokemon_place`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`roles` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`roles` (
  `rol_id` BIGINT NOT NULL AUTO_INCREMENT,
  `rol_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon_place`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`usuarios` (
  `usuario_id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_nombre` VARCHAR(120) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(150) NULL,
  `rol_id` BIGINT NOT NULL,
  PRIMARY KEY (`usuario_id`),
  CONSTRAINT `id_usuarios_roles`
    FOREIGN KEY (`rol_id`)
    REFERENCES `pokemon_place`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuarios_roles_idx` ON `pokemon_place`.`usuarios` (`rol_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pokemon_place`.`estado_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`estado_compra` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`estado_compra` (
  `estado_id` BIGINT NOT NULL AUTO_INCREMENT,
  `estado_compra` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon_place`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`compras` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`compras` (
  `compras_id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `fecha_compra` TIMESTAMP NULL,
  `estado_id` BIGINT NOT NULL,
  PRIMARY KEY (`compras_id`),
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `pokemon_place`.`usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estado_id`
    FOREIGN KEY (`estado_id`)
    REFERENCES `pokemon_place`.`estado_compra` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `usuario_id_idx` ON `pokemon_place`.`compras` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `estado_id_idx` ON `pokemon_place`.`compras` (`estado_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pokemon_place`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`categorias` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`categorias` (
  `categoria_id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon_place`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`productos` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`productos` (
  `producto_id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(200) NOT NULL,
  `precio` DECIMAL(9,2) NOT NULL,
  `categoria_id` BIGINT NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  PRIMARY KEY (`producto_id`),
  CONSTRAINT `categoria_id`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `pokemon_place`.`categorias` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `categoria_id_idx` ON `pokemon_place`.`productos` (`categoria_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pokemon_place`.`compras_has_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`compras_has_productos` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`compras_has_productos` (
  `compras_id` BIGINT NOT NULL AUTO_INCREMENT,
  `productos_id` BIGINT NOT NULL,
  `cantidad_compra` INT NOT NULL,
  PRIMARY KEY (`compras_id`, `productos_id`),
  CONSTRAINT `compras_id`
    FOREIGN KEY (`compras_id`)
    REFERENCES `pokemon_place`.`compras` (`compras_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`productos_id`)
    REFERENCES `pokemon_place`.`productos` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `producto_id_idx` ON `pokemon_place`.`compras_has_productos` (`productos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pokemon_place`.`imagenes_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon_place`.`imagenes_productos` ;

CREATE TABLE IF NOT EXISTS `pokemon_place`.`imagenes_productos` (
  `imagen_id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre_imagen` VARCHAR(120) NOT NULL,
  `producto_id` BIGINT NOT NULL,
  PRIMARY KEY (`imagen_id`),
  CONSTRAINT `id_imagen`
    FOREIGN KEY (`producto_id`)
    REFERENCES `pokemon_place`.`productos` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_imagen_idx` ON `pokemon_place`.`imagenes_productos` (`producto_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
